
const SIGNUP_REQUEST = "SIGNUP_REQUEST"
const SIGNUP_REQUEST_SUCESS = "SIGNUP_REQUEST_SUCESS"
const SIGNUP_REQUEST_FAILUE = "SIGNUP_REQUEST_FAILUE"

const LOGIN_REQUEST = "LOGIN_REQUEST"
const LOGIN_REQUEST_SUCESS = "LOGIN_REQUEST_SUCESS"
const LOGIN_REQUEST_FAILUE = "LOGIN_REQUEST_FAILUE"

const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST"
const FORGET_PASSWORD_REQUEST_SUCESS = "FORGET_PASSWORD_REQUEST_SUCESS"
const FORGET_PASSWORD_REQUEST_FAILUE = "FORGET_PASSWORD_REQUEST_FAILUE"

const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
const CHANGE_PASSWORD_REQUEST_SUCESS = "CHANGE_PASSWORD_REQUEST_SUCESS"
const CHANGE_PASSWORD_REQUEST_FAILUE = "CHANGE_PASSWORD_REQUEST_FAILUE"



const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
const RESET_PASSWORD_REQUEST_SUCESS = "RESET_PASSWORD_REQUEST_SUCESS"
const RESET_PASSWORD_REQUEST_FAILUE = "RESET_PASSWORD_REQUEST_FAILUE"

const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
const GET_PRODUCT_REQUEST_SUCESS = "GET_PRODUCT_REQUEST_SUCESS"
const GET_PRODUCT_REQUEST_FAILUE = "GET_PRODUCT_REQUEST_FAILUE"


const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
const GET_PRODUCT_DETAILS_REQUEST_SUCESS = "GET_PRODUCT_DETAILS_REQUEST_SUCESS"
const GET_PRODUCT_DETAILS_REQUEST_FAILUE = "GET_PRODUCT_DETAILS_REQUEST_FAILUE"

const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST"
const ADD_REVIEW_REQUEST_SUCESS = "ADD_REVIEW_REQUEST_SUCESS"
const ADD_REVIEW_REQUEST_FAILUE = "ADD_REVIEW_REQUEST_FAILUE"

const ADD_CART_REQUEST = "ADD_CART_REQUEST"
const ADD_CART_REQUEST_SUCESS = "ADD_CART_REQUEST_SUCESS"
const ADD_CART_REQUEST_FAILUE = "ADD_CART_REQUEST_FAILUE"

const GET_CART_REQUEST = "GET_CART_REQUEST"
const GET_CART_REQUEST_SUCESS = "GET_CART_REQUEST_SUCESS"
const GET_CART_REQUEST_FAILUE = "GET_CART_REQUEST_FAILUE"


const REMOVE_SINGLE_CART_REQUEST = "REMOVE_SINGLE_CART_REQUEST"
const REMOVE_SINGLE_CART_REQUEST_SUCESS = "REMOVE_SINGLE_CART_REQUEST_SUCESS"
const REMOVE_SINGLE_CART_REQUEST_FAILUE = "REMOVE_SINGLE_CART_REQUEST_FAILUE"


const REMOVE_ALL_CART_REQUEST = "REMOVE_ALL_CART_REQUEST"
const REMOVE_ALL_CART_REQUEST_SUCESS = "REMOVE_ALL_CART_REQUEST_SUCESS"
const REMOVE_ALL_CART_REQUEST_FAILUE = "REMOVE_ALL_CART_REQUEST_FAILUE"

const INCREMENT_CART_QUANTYTI_REQUEST = "INCREMENT_CART_QUANTYTI_REQUEST"
const INCREMENT_CART_QUANTYTI_REQUEST_SUCESS = "INCREMENT_CART_QUANTYTI_REQUEST_SUCESS"
const INCREMENT_CART_QUANTYTI_REQUEST_FAILUE = "INCREMENT_CART_QUANTYTI_REQUEST_FAILUE"

const DECREMENT_CART_QUANTYTI_REQUEST = "DECREMENT_CART_QUANTYTI_REQUEST"
const DECREMENT_CART_QUANTYTI_REQUEST_SUCESS = "DECREMENT_CART_QUANTYTI_REQUEST_SUCESS"
const DECREMENT_CART_QUANTYTI_REQUEST_FAILUE = "DECREMENT_CART_QUANTYTI_REQUEST_FAILUE"

const ADD_DELIVERY_ADDRESS_REQUEST = "ADD_DELIVERY_ADDRESS"
const ADD_DELIVERY_ADDRESS_SUCESS = "ADD_DELIVERY_ADDRESS"
const ADD_DELIVERY_ADDRESS_FAILURE = "ADD_DELIVERY_ADDRESS"



const ADD_WISHLIST_REQUEST = "ADD_WISHLIST_REQUEST"
const ADD_WISHLIST_REQUEST_SUCESS = "ADD_WISHLIST_REQUEST_SUCESS"
const ADD_WISHLIST_REQUEST_FAILUE = "ADD_WISHLIST_REQUEST_FAILUE"

const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST"
const GET_WISHLIST_REQUEST_SUCESS = "GET_WISHLIST_REQUEST_SUCESS"
const GET_WISHLIST_REQUEST_FAILUE = "GET_WISHLIST_REQUEST_FAILUE"

const REMOVE_WISHLIST_REQUEST = "REMOVE_WISHLIST_REQUEST"
const REMOVE_WISHLIST_REQUEST_SUCESS = "REMOVE_WISHLIST_REQUEST_SUCESS"
const REMOVE_WISHLIST_REQUEST_FAILUE = "REMOVE_WISHLIST_REQUEST_FAILUE"

const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST"
const ADD_ORDER_REQUEST_SUCCESS = "ADD_ORDER_REQUEST_SUCCESS"
const ADD_ORDER_REQUEST_FAILUE = "ADD_ORDER_REQUEST_FAILUE"

const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"
const GET_ORDERS_REQUEST_SUCCESS = "GET_ORDERS_REQUEST_SUCCESS"
const GET_ORDERS_REQUEST_FAILUE = "GET_ORDERS_REQUEST_FAILUE"


const GET_SINGLE_ORDER_REQUEST = "GET_SINGLE_ORDER_REQUEST"
const GET_SINGLE_ORDER_REQUEST_SUCCESS = "GET_SINGLE_ORDER_REQUEST_SUCCESS"
const GET_SINGLE_ORDER_REQUEST_FAILUE = "GET_SINGLE_ORDER_REQUEST_FAILUE"

const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST"
const CANCEL_ORDER_REQUEST_SUCCESS = "CANCEL_ORDER_REQUEST_SUCCESS"
const CANCEL_ORDER_REQUEST_FAILUE = "CANCEL_ORDER_REQUEST_FAILUE"

const LOGOUT_REQUEST = "LOGOUT_REQUEST"
const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS"
const LOGOUT_REQUEST_FAILUE = "LOGOUT_REQUEST_FAILUE"

const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
const DELETE_PRODUCT_REQUEST_SUCCESS = "DELETE_PRODUCT_REQUEST_SUCCESS"
const DELETE_PRODUCT_REQUEST_FAILUE = "DELETE_PRODUCT_REQUEST_FAILUE"


export {

    SIGNUP_REQUEST,
    SIGNUP_REQUEST_SUCESS,
    SIGNUP_REQUEST_FAILUE,

    LOGIN_REQUEST,
    LOGIN_REQUEST_SUCESS,
    LOGIN_REQUEST_FAILUE,

    FORGET_PASSWORD_REQUEST,
    FORGET_PASSWORD_REQUEST_SUCESS,
    FORGET_PASSWORD_REQUEST_FAILUE,

    RESET_PASSWORD_REQUEST,
    RESET_PASSWORD_REQUEST_SUCESS,
    RESET_PASSWORD_REQUEST_FAILUE,

    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_REQUEST_SUCESS,
    CHANGE_PASSWORD_REQUEST_FAILUE,



    GET_PRODUCT_REQUEST,
    GET_PRODUCT_REQUEST_SUCESS,
    GET_PRODUCT_REQUEST_FAILUE,

    GET_PRODUCT_DETAILS_REQUEST,
    GET_PRODUCT_DETAILS_REQUEST_SUCESS,
    GET_PRODUCT_DETAILS_REQUEST_FAILUE,

    ADD_REVIEW_REQUEST,
    ADD_REVIEW_REQUEST_SUCESS,
    ADD_REVIEW_REQUEST_FAILUE,

    ADD_CART_REQUEST,
    ADD_CART_REQUEST_SUCESS,
    ADD_CART_REQUEST_FAILUE,

    GET_CART_REQUEST,
    GET_CART_REQUEST_SUCESS,
    GET_CART_REQUEST_FAILUE,

    REMOVE_SINGLE_CART_REQUEST,
    REMOVE_SINGLE_CART_REQUEST_SUCESS,
    REMOVE_SINGLE_CART_REQUEST_FAILUE,

    REMOVE_ALL_CART_REQUEST,
    REMOVE_ALL_CART_REQUEST_SUCESS,
    REMOVE_ALL_CART_REQUEST_FAILUE,

    INCREMENT_CART_QUANTYTI_REQUEST,
    INCREMENT_CART_QUANTYTI_REQUEST_SUCESS,
    INCREMENT_CART_QUANTYTI_REQUEST_FAILUE,

    DECREMENT_CART_QUANTYTI_REQUEST,
    DECREMENT_CART_QUANTYTI_REQUEST_SUCESS,
    DECREMENT_CART_QUANTYTI_REQUEST_FAILUE,

    ADD_DELIVERY_ADDRESS_REQUEST,
    ADD_DELIVERY_ADDRESS_SUCESS,
    ADD_DELIVERY_ADDRESS_FAILURE,

    ADD_WISHLIST_REQUEST,
    ADD_WISHLIST_REQUEST_SUCESS,
    ADD_WISHLIST_REQUEST_FAILUE,

    GET_WISHLIST_REQUEST,
    GET_WISHLIST_REQUEST_SUCESS,
    GET_WISHLIST_REQUEST_FAILUE,

    REMOVE_WISHLIST_REQUEST,
    REMOVE_WISHLIST_REQUEST_SUCESS,
    REMOVE_WISHLIST_REQUEST_FAILUE,

    ADD_ORDER_REQUEST,
    ADD_ORDER_REQUEST_SUCCESS,
    ADD_ORDER_REQUEST_FAILUE,

    GET_ORDERS_REQUEST,
    GET_ORDERS_REQUEST_SUCCESS,
    GET_ORDERS_REQUEST_FAILUE,

    GET_SINGLE_ORDER_REQUEST,
    GET_SINGLE_ORDER_REQUEST_SUCCESS,
    GET_SINGLE_ORDER_REQUEST_FAILUE,

    CANCEL_ORDER_REQUEST,
    CANCEL_ORDER_REQUEST_SUCCESS,
    CANCEL_ORDER_REQUEST_FAILUE,

    LOGOUT_REQUEST,
    LOGOUT_REQUEST_SUCCESS,
    LOGOUT_REQUEST_FAILUE,

    DELETE_PRODUCT_REQUEST,
    DELETE_PRODUCT_REQUEST_SUCCESS,
    DELETE_PRODUCT_REQUEST_FAILUE

}